### PR TITLE
[Bug] Blackout configuration blocking class registrations outside range

### LINKED ISSUE #166: [Bug] Blackout configuration blocking class registrations outside the blackout range
Creating a blackout configuration "Offices Closed" for, say, Friday 2 p.m. to 6 p.m. will block morning classes for that same day that are not included in the blackout

Trello Issue #`QXy0m8BR`

### PR DESCRIPTION
**Pull request by Evilscaught**
Closes #166

**_Action_**
Requesting to merge branch `bug/#166-blackout-configuration-blocking-class-registrations-outside-range` into `master`

**_Description_**
Added a new test "should not block out classes outside a blackout class exception" which will fail if a class is getting blocked by a blackout and shouldn't be.

ℹ️ Blackout and class is for the same day, class spans morning to evening and blackout only applies in the evening.

### CODE REVIEW

File: api/availability/test.js [hunk 1]
```diff
@@ -437,4 +555,4 @@ describe('Acceptance :: Routes :: availability', () => {
       });
     });
   });
-});
+});
```
Comment (JavaLavaMT) [inline api/availability/test.js]:
```suggestion
});

```

File: api/hub-classes/index.js [hunk 2]
```diff
@@ -141,3 +141,4 @@ exports.withAvailability = async function (n, HubClass, compiledQuery) {
     hubClass: hubClasses
   };
 };
+
```
Comment (JavaLavaMT) [inline api/hub-classes/index.js]:
```suggestion
 
 
```

File: api/availability/test.js [hunk 3]
```diff
@@ -174,6 +174,124 @@ describe('Acceptance :: Routes :: availability', () => {
...
+        ];
+
+        // classExceptions means "blackout everything EXCEPT these classes"
+        // So regularClass1 is allowed, all others are blocked
+        yield (new BlackoutDate({
+          start: moment(dec).date(thursday).startOf('day').toDate(),
+          end: moment(dec).date(thursday).endOf('day').toDate(),
+          classExceptions: [regularClass1._id],
+          blocks
+        })).save();
```
[the remark this answers is not in the document]
Comment (Evilscaught) [reply api/availability/test.js:217]: Blackouts with classExceptions is inverted
